### PR TITLE
Add pagination to myFollowers

### PR DESCRIPTION
**Pull request by andrewschreiber**
Follows style of `myIssues` in Issues.swift

### CODE REVIEW

**Comment by andrewschreiber** [comment]
Noticed tests are failing, specifically with this error:

`Test Case '-[OctoKitTests.FollowTests testGetMyFollowers]' started.`
`2016-05-10 02:19:22.967 xctest[66737:1793820] *** Terminating app due to uncaught exception 'NocillaUnexpectedRequest', reason: 'An unexpected HTTP request was fired.`

I'm not familiar with Nocilla, so it's not clear to me what's causing the problem here.

**Comment by pietbrauer** [comment]
You make a HTTP request that is not stubbed, probably because there is a new parameter in the call. It should also fail locally in Xcode.

**Comment by andrewschreiber** [comment]
Thanks, that makes sense. Will take another look in the light of day.

**Comment by pietbrauer** [comment]
Ping 📲

**Comment by pietbrauer** [comment]
Timed out, please reopen if you feel like continuing.

**Pull request closed without merging**
