### PR TITLE
Documentation for most of the implemented API

### PR DESCRIPTION
**Pull request by nwest**
It might be neat to use https://github.com/realm/jazzy for a docs site.

### CODE REVIEW

**Comment by nwest** [comment]
This needs https://github.com/nerdishbynature/octokit.swift/commit/c59f701c9a32447ccac56f264d88d9a6b280bc0b to go green again.

**Comment by pietbrauer** [comment]
AFAIK cocoa pods uses jazzy and docs will be at http://cocoadocs.org/docsets/NBNRequestKit/0.1.0/. Would it be nice to include code examples? I kind of liked the documentation in the README tbh. But then I am not a fan of documentation either. We should decide on one way and then remove the docs from the README as documenting it twice is not very sufficient.

**Comment by nwest** [comment]
I actually started working on this because I wanted to try out jazzy, I didn't realize it gets generated when you push it to cocoapods. 

It's possible to put code examples in the inline docs, which we could do. Another nice thing is that the docs show up when you option click classes and functions in Xcode. 

If you're not a fan of inline docs and would prefer to keep the README style, we can close this. I'm not set on it.

**Comment by pietbrauer** [comment]
Nice, didn't realise the Xcode alt+click documentation is done automatically. Could you indent the lines so the comments `/**` start on the same indentation spot as the `func` definitions?

**Comment by nwest** [comment]
Markdown works, too.

screen shot 2015-11-25 at 8 02 31 am

**Comment by pietbrauer** [comment]
Super good, thanks a lot! Will push version 0.5.0 tomorrow then!

**Pull request merged**
