### PR TITLE
Enable async/await on Linux

### PR DESCRIPTION
**Pull request by 417-72KI**
Same fix as https://github.com/nerdishbynature/RequestKit/pull/85

## Note:
~~Although the based PR has been merged, it has not been released yet.~~
~~This PR requires a new release which contains it.~~

### CODE REVIEW

**Comment by pietbrauer** [comment]
OMG this was open for so long and I completely missed this 🤦 .
Seems that I will create a new RequestKit release tomorrow and merge this.

Thanks a lot!

**Comment by pietbrauer** [comment]
@417-72KI I released RequestKit 3.2.0. Could you update the PR?

**Comment by 417-72KI** [comment]
@pietbrauer 
Many thanks!
I updated dependencies and it's ready for review!

**Review by pietbrauer — APPROVED** [review]

**Comment by pietbrauer** [comment]
Thanks a lot! ✨

**Pull request merged**
