### PR TITLE
Add Issue files to the .xcodeproj

### PR DESCRIPTION
**Pull request by nwest**
I also moved `issue.json` to the Fixtures folder.

### CODE REVIEW

**Comment by pietbrauer** [comment]
Have you moved it to all 4 targets? Mac, iOS, tvOS and Watch?

**Comment by nwest** [comment]
Ah thank you. I still haven't had my coffee this morning.

**Comment by nwest** [comment]
@pietbrauer good to go?

**Comment by pietbrauer** [comment]
Looks good! 🤘

**Pull request merged**
