### PR TITLE
Support for Issues

### PR DESCRIPTION
**Pull request by thomaspaulmann**
This PR will close Issue #33. Pull Requests are a part of the Issues. I will add them in a separated PR.

### CODE REVIEW

**Comment by pietbrauer** [comment]
👍 Looks legit, waiting for Travis.

**Comment by nwest** [comment]
We might need to distinguish that this is for https://github.com/issues and not https://github.com/nerdishbynature/octokit.swift/issues, for e.g.

**Comment by pietbrauer** [comment]
@nwest Ha, good catch!

**Comment by pietbrauer** [comment]
@thomaspaulmann Could you maybe change it to be like [repositories](https://github.com/nerdishbynature/octokit.swift/blob/master/OctoKit/Repositories.swift#L55-L58) and could you perhaps add some documentation for the README?

**Comment by thomaspaulmann** [comment]
@nwest good one, I will change it and I've already added some documentation in the README

**Comment by thomaspaulmann** [comment]
@nwest Does that fit your expectations?

**Comment by nwest** [comment]
Ah, I wasn't very clear. See here: https://developer.github.com/v3/issues/#list-issues This PR implements `GET /user/issues`. There's also `GET /orgs/:org/issues`, `GET /issues`, and `GET /repos/:owner/:repo/issues`. You don't have to implement the other methods in this PR, we'll just have to differentiate them. 

Maybe add something like "Get issues across owned and member repositories for the authenticated user" to the README?

**Comment by nwest** [comment]
Thanks @thomaspaulmann!

**Comment by pietbrauer** [comment]
Ha, there was no change to the project file?

**Comment by nwest** [comment]
@pietbrauer oops, I'll patch it.

**Pull request merged**
