### PR TITLE
Pull request basic support

### PR DESCRIPTION
**Pull request by polok**
Basic support for getting basic information about single pull request or a list of pull requests

### CODE REVIEW

**Comment by pietbrauer** [comment]
Thanks for the PullRequest! I hope I will find time until end of the week to look at it. But looks promising on the first look 🙏🙏

**Comment by polok** [comment]
You're welcome. Anyway, If you find something suspicious, just let me know ;)

**Comment by polok** [comment]
😄

**Comment by polok** [comment]
@pietbrauer Thanks for the invitation!

**Comment by pietbrauer** [comment]
Sure 👍 I value your contribution!

**Pull request merged**
