### PR TITLE
Add Swift 5.1 support on Linux

### PR DESCRIPTION
**Pull request by ellneal**
Uses the `FoundationNetworking` module where available.

### CODE REVIEW

**Comment by ellneal** [comment]
@f-meloni I actually did this to get my fork of danger building on linux with Swift 5.1 (and you're right that this is the last thing missing) 😂 

I was going to wrap these in `#if os(Linux)` but thought it could get a bit ugly, so was waiting for feedback from the maintainers before making it even uglier 😄

**Comment by f-meloni** [comment]
I think `#if os(Linux)` would not work because swift doesn't have `FoundationNetworking` before swift 5.1

**Comment by JosephDuffy** [comment]
Is there an option to drop Xcode 9.2?

Swift 4.1 (which is when `canImport` was introduced, according to [SE-0075](https://github.com/apple/swift-evolution/blob/master/proposals/0075-import-test.md)) requires Xcode 9.3, but it could also be argued that only Xcode 10 and Xcode 11 are to be supported (last 2 major versions)

**Comment by pietbrauer** [comment]
I would rather support iOS versions than Xcode versions. I think it’s ok to support only iOS 10, 11 and 12.

**Comment by ellneal** [comment]
Switching to Xcode 11 has just created a hang when installing gems. I'll look into it when I have some free time.

**Comment by pietbrauer** [comment]
Maybe you can take a hint from RequestKit as we are on 10.2 “already”. I also have an open pull request which is failing for a different reason using Xcode 11.2

https://github.com/nerdishbynature/RequestKit

**Comment by ellneal** [comment]
I have actually managed to get all the tests to pass now, but it’s timing out when attempting to lint the pod spec 🤦‍♂️

**Comment by pietbrauer** [comment]
Yes, so same as on RequestKit. Maybe disable it for now and open an issue so we can move on?

**Comment by ellneal** [comment]
@pietbrauer it looks to me as if this is all controlled from the [nerdishbynature/requestkit_fastlane](https://github.com/nerdishbynature/requestkit_fastlane) repository. My experience with Fastlane is entirely contained within the commits in this PR, so I'm not sure I'm the best person for the job 😅

**Comment by ellneal** [comment]
I've managed to disable the `pod spec lint` step by removing the `DEPLOY_PODSPEC` environment variable 🎉

**Comment by ellneal** [comment]
@pietbrauer No worries 😁 Can you tag a new release? I'll open an issue to re-enable the podspec linting 👍

**Comment by f-meloni** [comment]
Yeah a new release would be great 🚀

**Comment by pietbrauer** [comment]
@ellneal @f-meloni Done

**Pull request merged**
