### PR TITLE
Fix swift build

### LINKED ISSUE #101: Error running swift build after Xcode 11.4 update
Error message:
`'OctoKit' ***/.build/checkouts/octokit.swift: error: target at '/ ***/.build/checkouts/octokit.swift' contains mixed language source files; feature not supported`

Blocking https://github.com/danger/swift/issues/327

### PR DESCRIPTION
**Pull request by bofeizhu**
Fixed #101

### CODE REVIEW

**Comment by bofeizhu** [comment]
I don't know why Travis kept running on the Xcode9 image.

**Comment by pietbrauer** [comment]
Thanks for the effort but I have a hard time to process what the actual problem was.

1. You moved all files to `Sources` and removed the custom path from the Swift package -> Why?
2. Readded all files to the Xcodeproj -> How is this related to SwiftPM?
3. Introduced redundancy in the `.travis.yml`

Please help me understand so we can get this fixed for Danger.

**Comment by bofeizhu** [comment]
Hi Piet, for 1, I don’t know if it’s a bug introduced in Swift 5.2 (Xcode 11.4) or if it’s a change of design. The new SPM includes the .h and .plist files if we refer the source files by path and root. That’s why I moved source files to the SPM’s default directory (`Sources/PackageName`) and that fixed #101.

2. Because of 1, I have to update the xcodeproj to refer to new file locations.

3. You can refer to my comment on top. Travis failed to initiate the correct Xcode image last night for my PR. You can refer to the Travis logs of my early commits in this PR. When default language was set to generic, it initiated Xcode 9 image for all the macOS workers. Updated the language to swift solved this issue. I’m not an expert of Travis so I’m not sure if this is a bug/permanent change on their end.

**Comment by bofeizhu** [comment]
@pietbrauer bump ^ just in case you missed my comment 😉.

**Comment by MaxDesiatov** [comment]
Hope this can be merged soon, as it blocks [GitBuddy](https://github.com/WeTransfer/GitBuddy) from building with Xcode 11.4

**Comment by Killectro** [comment]
It also blocks [Danger Homebrew Tap](https://github.com/danger/homebrew-tap) as well.

**Comment by f-meloni** [comment]
@bofeizhu I think you should be able to restore `travis`, I saw some issues with it before, but it looks working again

**Comment by bofeizhu** [comment]
@f-meloni Just tried, not working... Have to set language to Swift https://travis-ci.org/github/nerdishbynature/octokit.swift/builds/668130190?utm_source=github_status&utm_medium=notification
As you can see here, the Xcode 9 image is used when I reverse the language to generic. I think this is a relatively new bug in Travis.

**Comment by bofeizhu** [comment]
@pietbrauer I updated the `.travis.yml` again. I believe this is the version with the least redundancy that can workaround Travis's bug at the moment. cc @f-meloni

**Comment by pietbrauer** [comment]
I've been working on a less invasive approach (#103) where all files stay in place and the only thing that changes is the one causing the problem, `Package.swift`.

@bofeizhu Could you please have a look if this fixes your problem? I am also happy to merge your PR once it restores the original structure.

**Comment by bofeizhu** [comment]
@pietbrauer LGTM! I'm closing this PR. Please merge #103 instead.

**Pull request closed without merging**
