### PR TITLE
add some more fields to repo, and structure for organization

### PR DESCRIPTION
**Pull request by armcknight**
Hi @nerdishbynature, thanks for offering this package. I had a need for a few extra things from it, so wanted to offer this PR. Thanks!

### CODE REVIEW

**Comment by pietbrauer** [comment]
Thanks for the PR. Some tests would be nice!

**Comment by armcknight** [comment]
Added tests! While resolving the conflict I realized I had duplicated the functionality in Stars.swift in new functionality in Repositories.swift, so I removed mine.

**Comment by armcknight** [comment]
Is there a reason NotificationTests.swift isn't part of the Xcode project and only runs in the SPM tests?

**Comment by pietbrauer** [comment]
> Is there a reason NotificationTests.swift isn't part of the Xcode project and only runs in the SPM tests?

No particular reason. I guess someone just forgot to add it as it's very easy to forget nowadays with Xcode opening the project as a package first. We can get rid of the Xcode Project at some point if we only want to support SPM and discard Carthage.

Search Tests seem to fail for some reason once it's ready we can merge it.

**Comment by armcknight** [comment]
Fixed the remaining issues @pietbrauer! One question, have you ever considered using [pre-commit](https://pre-commit.com/hooks.html) so the lint issues don't present an extra CI run? (see Swiftformat's docs on it: https://github.com/nicklockwood/SwiftFormat?tab=readme-ov-file#git-pre-commit-hook)

**Review by pietbrauer — APPROVED** [review]
Thanks a lot! I am personally not a huge fan of pre-commit hooks as it requires people to have the tool installed to make a commit.

**Pull request merged**
