### PR TITLE
Update URLSession.shared API

### PR DESCRIPTION
**Pull request by phatblat**
Changed in Xcode 8 beta 2

### CODE REVIEW

**Comment by pietbrauer** [comment]
We are waiting for the Travis update, I guess?

**Comment by phatblat** [comment]
The RequestKit clone is failing

```
*** Cloning RequestKit
*** Skipped downloading RequestKit.framework binary due to the error:
	"Maximum number of login attempts exceeded. Please try again later."
```

**Comment by phatblat** [comment]
OK, I'm tired and didn't read that correctly. The binary download failed but the clone succeeded.

**Comment by phatblat** [comment]
RequestKit updated with nerdishbynature/RequestKit#22. Build is green so this PR is ready for review.

**Comment by pietbrauer** [comment]
Sweet :sparkles:

**Pull request merged**
