### PR TITLE
Add `perPage` argument to list releases, delete release, delete reference endpoints

### PR DESCRIPTION
**Pull request by AvdLee**
- [x] Adds a `perPage` parameter to the list releases endpoint
- [x] Adds the delete release endpoint
- [x] Adds the delete reference endpoint

I did not add tests for the deletion endpoints since they require decoding and would not leave much of a valuable unit test looking at the other written unit tests. 
The test for the releases per page argument has been updated accordingly.

### CODE REVIEW

**Comment by pietbrauer** [comment]
I try to have a look today but the linting fails, please make sure you run swift format.

**Comment by AvdLee** [comment]
@pietbrauer missed that! Just applied SwiftFormat, so it should look good now 💪

**Review by pietbrauer — APPROVED** [review]

**Comment by pietbrauer** [comment]
Linting still fails 🙃

**Comment by AvdLee** [comment]
> Linting still fails 🙃

@pietbrauer is there any other script that I need to run other than SwiftFormat? There's nothing more to lint there:

```
avanderlee@Antoines-MBP octokit.swift % swiftformat .
Running SwiftFormat...
Reading config file at /Users/avanderlee/Developer/GIT-Projects/Forks/octokit.swift/.swiftformat
SwiftFormat completed in 0.7s.
0/45 files formatted, 2 files skipped.
```

**Comment by pietbrauer** [comment]
We always install the latest version on CI. Maybe you are running an old version? Happened to me before…

**Comment by AvdLee** [comment]
> We always install the latest version on CI. Maybe you are running an old version? Happened to me before…

That indeed turned out to be the case, I didn't think about that! Thanks for the suggestion 💪 
CI is running 🚀

**Review by pietbrauer — APPROVED** [review]

**Pull request merged**
